/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.bthd.borratuhuelladigital;

/**
 *
 * @author jaxt3
 */
public class cookiesPrivacidad extends javax.swing.JFrame {

    /**
     * Creates new form cookiesPrivacidad
     */
    public cookiesPrivacidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPrueba1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        ckP1 = new javax.swing.JCheckBox();
        ckP2 = new javax.swing.JCheckBox();
        ckP5 = new javax.swing.JCheckBox();
        ckP3 = new javax.swing.JCheckBox();
        ckP4 = new javax.swing.JCheckBox();
        btnFormularioListo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ckPrueba1 = new javax.swing.JCheckBox();
        ckPrueba5 = new javax.swing.JCheckBox();
        ckPrueba2 = new javax.swing.JCheckBox();
        ckPrueba3 = new javax.swing.JCheckBox();
        ckPrueba4 = new javax.swing.JCheckBox();
        btnConfirmarPrueba1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ckPrueba6 = new javax.swing.JCheckBox();
        ckPrueba10 = new javax.swing.JCheckBox();
        ckPrueba7 = new javax.swing.JCheckBox();
        ckPrueba8 = new javax.swing.JCheckBox();
        ckPrueba9 = new javax.swing.JCheckBox();
        btnConfirmarPrueba2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(187, 208, 214));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Evaluación de Cookies y Uso de Información");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PRIVACIDAD");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(187, 208, 214));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Evaluación");

        ckP1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ckP1.setForeground(new java.awt.Color(0, 0, 0));
        ckP1.setText("Las cookies de terceros son utilizadas para rastrear tus actividades en varios sitios web");

        ckP2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ckP2.setForeground(new java.awt.Color(0, 0, 0));
        ckP2.setText("Aceptar todas las cookies siempre garantiza tu privacidad y seguridad online");

        ckP5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ckP5.setForeground(new java.awt.Color(0, 0, 0));
        ckP5.setText("Las cookies solo se utilizan para mejorar la funcionalidad del sitio web y nunca para rastrear a los usuarios");

        ckP3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ckP3.setForeground(new java.awt.Color(0, 0, 0));
        ckP3.setText("Las cookies pueden recopilar información como tu ubicación y hábitos de navegación");
        ckP3.setActionCommand("");

        ckP4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        ckP4.setForeground(new java.awt.Color(0, 0, 0));
        ckP4.setText("Es posible gestionar las cookies para reducir el seguimiento de tu actividad en línea");
        ckP4.setActionCommand("");

        btnFormularioListo.setBackground(new java.awt.Color(255, 255, 255));
        btnFormularioListo.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        btnFormularioListo.setForeground(new java.awt.Color(0, 0, 0));
        btnFormularioListo.setText("LISTO");
        btnFormularioListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormularioListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFormularioListo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(ckP2)
                                    .addComponent(ckP5)
                                    .addComponent(ckP3)
                                    .addComponent(ckP4))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckP4)
                .addGap(8, 8, 8)
                .addComponent(ckP5)
                .addGap(18, 18, 18)
                .addComponent(btnFormularioListo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 192, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Evaluación", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(187, 208, 214));

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("  paginasospechosa.cbtis03.edu.mx");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ckPrueba1.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba1.setText("Mantener sesión iniciada");
        ckPrueba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPrueba1ActionPerformed(evt);
            }
        });

        ckPrueba5.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba5.setText("No aceptar ninguno");

        ckPrueba2.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba2.setText("Mejorar el sitio con tus datos\t");

        ckPrueba3.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba3.setText("Mostrar anuncios basados en tu actividad\t");

        ckPrueba4.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba4.setSelected(true);
        ckPrueba4.setText("Aceptar Todos");

        btnConfirmarPrueba1.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirmarPrueba1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnConfirmarPrueba1.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarPrueba1.setText("CONFIRMAR");
        btnConfirmarPrueba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPrueba1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(ckPrueba5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckPrueba2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckPrueba3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmarPrueba1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ckPrueba1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ckPrueba4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(ckPrueba2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckPrueba3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(ckPrueba5)
                .addGap(1, 1, 1)
                .addComponent(btnConfirmarPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(ckPrueba1)
                    .addContainerGap(171, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(161, Short.MAX_VALUE)
                    .addComponent(ckPrueba4)
                    .addGap(73, 73, 73)))
        );

        jPanel6.setBackground(new java.awt.Color(187, 208, 214));

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("feriaespecialidades.cbtis03.edu.mx");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ckPrueba6.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba6.setText("Guardar configuraciones de tu navegador");
        ckPrueba6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPrueba6ActionPerformed(evt);
            }
        });

        ckPrueba10.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba10.setText("No aceptar ninguno");

        ckPrueba7.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba7.setText("Aceptar nuestras cookies necesarias y esenciales");

        ckPrueba8.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba8.setText("Permitir análisis de comportamiento entre páginas");

        ckPrueba9.setForeground(new java.awt.Color(0, 0, 0));
        ckPrueba9.setSelected(true);
        ckPrueba9.setText("Aceptar Todos");

        btnConfirmarPrueba2.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirmarPrueba2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnConfirmarPrueba2.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirmarPrueba2.setText("CONFIRMAR");
        btnConfirmarPrueba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPrueba2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(ckPrueba10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckPrueba7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckPrueba8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmarPrueba2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ckPrueba6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ckPrueba9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(ckPrueba7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckPrueba8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ckPrueba10)
                .addGap(1, 1, 1)
                .addComponent(btnConfirmarPrueba2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(ckPrueba6)
                    .addContainerGap(183, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(173, Short.MAX_VALUE)
                    .addComponent(ckPrueba9)
                    .addGap(73, 73, 73)))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(187, 208, 214));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("\nRevisa las opciones personalizadas: No aceptes todas las cookies automáticamente, selecciona solo las necesarias para el funcionamiento del sitio.\n\nDesactiva cookies de seguimiento: Si el sitio ofrece la opción, evita aceptar cookies relacionadas con anuncios o análisis de comportamiento.\n\nLee la política de cookies: Dedica unos minutos a entender cómo se utilizarán tus datos antes de aceptar.\n\nUtiliza el modo incógnito: Para evitar el almacenamiento de cookies, navega en modo privado o incógnito.\n\nConfigura tu navegador: Ajusta las preferencias de privacidad para bloquear cookies de terceros de manera predeterminada.\n\nLimpia tus cookies regularmente: Borra cookies y datos del navegador de forma periódica para limitar el rastreo.\n\nUsa extensiones de privacidad: Instala herramientas como Privacy Badger o uBlock Origin para gestionar y bloquear cookies no deseadas.\n\nDesconfía de sitios desconocidos: Evita aceptar cookies en páginas que parezcan sospechosas o poco confiables.\n\nElige \"No aceptar\" si no es necesario: Si puedes usar el sitio sin aceptar cookies opcionales, hazlo.\n\nDesactiva cookies opcionales después de usarlas: Si necesitas habilitar cookies momentáneamente, recuerda desactivarlas al terminar.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Recomendaciones Adicionales");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(244, 244, 244))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Prácticas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormularioListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormularioListoActionPerformed
        boolean[] respuestasPrivacidadDefault = {true, false, true, true, false};
        boolean[] respuestasPrivacidad = {ckP1.isSelected(),ckP2.isSelected(),ckP3.isSelected(),ckP4.isSelected(),ckP5.isSelected()};

        int respuestasCorrectas = 0;
        for (int i = 0; i < respuestasPrivacidadDefault.length; i++) {
            if (respuestasPrivacidadDefault[i] == respuestasPrivacidad[i]) {
                respuestasCorrectas++;
            }
        }

        String mensajeResultado = "Has respondido " + respuestasCorrectas + " de "+ respuestasPrivacidadDefault.length + " preguntas correctamente.";

        if (respuestasCorrectas == respuestasPrivacidadDefault.length) {
            mensajeResultado += "\n¡Excelente trabajo! Entiendes bien cómo afectan las cookies a tu privacidad.";
        } else if (respuestasCorrectas >= 3) {
            mensajeResultado += "\nBuen intento, pero puedes aprender más sobre la gestión de cookies.";
        } else {
            mensajeResultado += "\nEs importante que aprendas más sobre cómo las cookies afectan tu privacidad.";
        }

        javax.swing.JOptionPane.showMessageDialog(this, mensajeResultado, "Resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        ckP1.setSelected(false);
        ckP2.setSelected(false);
        ckP3.setSelected(false);
        ckP4.setSelected(false);
        ckP5.setSelected(false);          
    }//GEN-LAST:event_btnFormularioListoActionPerformed

    private void ckPrueba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPrueba1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckPrueba1ActionPerformed

    private void btnConfirmarPrueba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPrueba1ActionPerformed
        boolean[] respuestasPrueba1Default = {true,false,false,false,false};
        boolean[] respuestasPrueba1 = {ckPrueba1.isSelected(),ckPrueba2.isSelected(),ckPrueba3.isSelected(),ckPrueba4.isSelected(),ckPrueba5.isSelected()};
       
        int respuestasCorrectas = 0;
        for (int i = 0; i < respuestasPrueba1Default.length; i++) {
            if (respuestasPrueba1Default[i] == respuestasPrueba1[i]) {
                respuestasCorrectas++;
            }
        }
        
    String mensajeResultado = "Has respondido " + respuestasCorrectas + " de " + respuestasPrueba1Default.length + " preguntas correctamente.";

    if (respuestasCorrectas == respuestasPrueba1Default.length) {
        mensajeResultado += "\n¡Excelente trabajo! Entiendes bien cómo afectan las cookies a tu privacidad.";
    } else if (respuestasCorrectas >= 3) {
        mensajeResultado += "\nBuen intento, pero puedes aprender más sobre la gestión de cookies.";
    } else {
        mensajeResultado += "\nEs importante que aprendas más sobre cómo las cookies afectan tu privacidad.";
    }

    javax.swing.JOptionPane.showMessageDialog(this, mensajeResultado, "Resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    ckPrueba1.setSelected(false);
    ckPrueba2.setSelected(false);
    ckPrueba3.setSelected(false);
    ckPrueba4.setSelected(true);
    ckPrueba5.setSelected(false);   
        
    }//GEN-LAST:event_btnConfirmarPrueba1ActionPerformed

    private void ckPrueba6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPrueba6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckPrueba6ActionPerformed

    private void btnConfirmarPrueba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPrueba2ActionPerformed
        boolean[] respuestasPrueba2Default = {true,true,false,false,false};
        boolean[] respuestasPrueba2 = {ckPrueba6.isSelected(),ckPrueba7.isSelected(),ckPrueba8.isSelected(),ckPrueba9.isSelected(),ckPrueba10.isSelected()};
       
        int respuestasCorrectas = 0;
        for (int i = 0; i < respuestasPrueba2Default.length; i++) {
            if (respuestasPrueba2Default[i] == respuestasPrueba2[i]) {
                respuestasCorrectas++;
            }
        }
        
    String mensajeResultado = "Has respondido " + respuestasCorrectas + " de " + respuestasPrueba2Default.length + " preguntas correctamente.";

    if (respuestasCorrectas == respuestasPrueba2Default.length) {
        mensajeResultado += "\n¡Excelente trabajo! Entiendes bien cómo afectan las cookies a tu privacidad.";
    } else if (respuestasCorrectas >= 3) {
        mensajeResultado += "\nBuen intento, pero puedes aprender más sobre la gestión de cookies.";
    } else {
        mensajeResultado += "\nEs importante que aprendas más sobre cómo las cookies afectan tu privacidad.";
    }

    javax.swing.JOptionPane.showMessageDialog(this, mensajeResultado, "Resultados", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    ckPrueba6.setSelected(false);
    ckPrueba7.setSelected(false);
    ckPrueba8.setSelected(false);
    ckPrueba9.setSelected(true);
    ckPrueba10.setSelected(false);   
        
    }//GEN-LAST:event_btnConfirmarPrueba2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cookiesPrivacidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cookiesPrivacidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cookiesPrivacidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cookiesPrivacidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cookiesPrivacidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPrueba1;
    private javax.swing.JButton btnConfirmarPrueba1;
    private javax.swing.JButton btnConfirmarPrueba2;
    private javax.swing.JButton btnFormularioListo;
    private javax.swing.JCheckBox ckP1;
    private javax.swing.JCheckBox ckP2;
    private javax.swing.JCheckBox ckP3;
    private javax.swing.JCheckBox ckP4;
    private javax.swing.JCheckBox ckP5;
    private javax.swing.JCheckBox ckPrueba1;
    private javax.swing.JCheckBox ckPrueba10;
    private javax.swing.JCheckBox ckPrueba2;
    private javax.swing.JCheckBox ckPrueba3;
    private javax.swing.JCheckBox ckPrueba4;
    private javax.swing.JCheckBox ckPrueba5;
    private javax.swing.JCheckBox ckPrueba6;
    private javax.swing.JCheckBox ckPrueba7;
    private javax.swing.JCheckBox ckPrueba8;
    private javax.swing.JCheckBox ckPrueba9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
